env: ppe
portal:
  msit: https://msit.microsoftstream.com
  ppe: https://ppe.microsoftstream.com
  srol1: https://web-srol-1.stream.azure-test.net
  srol2: https://web-srol-2.stream.azure-test.net
  refe: https://web-refe-1.stream.azure-test.net
user:
  test1: test1@media.ccsctp.net
  test2: test2@media.ccsctp.net
  test3: test3@media.ccsctp.net
  test4: test4@media.ccsctp.net
  test5: test5@media.ccsctp.net
  tenantadmin: tenantadmin@media.ccsctp.net
  streamadmin: streamadmin@media.ccsctp.net
  personalAccount: XXX@microsoft.com
pwd:
  commonpwd: XXXX
implicitly_wait: 120
verify:
  ppe: '@msft.sts.microsoft.com/adfs/ls/wia?client-request-id=e61fae8f-0134-4925-957f-6bfe94db0abc&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAYWSPYzSYBzGKdzhHfHjYoxxk0EXL4W3lJYeySUeUI5yUChfLV1IoW-Pfr6lLR9lcXXzBo2Jg4PjDQ7GwRhNXIzJTZe4nZuDw03GyckIi6vLf_n_8gzP73kQI1JE_t5Io0htBBlchRqNZxU4xBmVBPiQoBiYGxIjjSGrcQqALEV6NxM7T17f_ZHF7nPPHpl_nn5LfDjFkuMgcP18Ou26MGXrIw_5SAv8wIOKnRohO_0Ow84x7DTq02SOzAJAUoABNEUCCqT6dtniS2OzLnJBQ2zZ_RAA3uguaiK3lEsHQd3g7XpnlJEN3qrbZV026iFvcCG__nV6Nl9c8R0WrPhsQxQCftmy5JK8yuyZdaO7vIjeaBxMg3FmfZCnL-Gv6LaGPHvgIj94EXsebbjQ4dQichw4ClJrDDqBPlICHTlND7nQC3To74c-HuaqDFWpmSrj19quN57OQ1hk26h81LTYuaCiQzMktCbr8A454fmyYRa6S5ntz5iF0NvzcQ6gcVEu52QkFbmpMxWsvtNR-np1kGnMKFTstyeledjyWE6EnlPxJULKqV0DV8Zs6B5mKu2BnK0oqLlQj5wyrXh84EyqlSwpS7ljybQnlQY9m1E0Yg1_2B6Lc2fITw-Xx1ZVEReV5VCrkUyhSgilYVsH5p6idqRe4NUnlAYWR4bQHexxhFBgrawoHrSlN7H4yp2NnLPY9VUJjq4mXQ9pugW_x27P8FDXoHP88J_utejzDexy4yqI5be2EjuRO5Fk5PcG9mpzNZrY149fKP2ydvqSR28_n0fONtOt4UzVBZrvtDQklUOZLUkFyzOLrGJ1oRU2NcDtlrRdXbHr-5k8cRLHTuLxn3Hs8ZXI--3_Tu4icSsDMgAHDJ6hk4DIU6sMWv50LfIX0&cbcxt=&username=v-yifeng%40microsoft.com&mkt=&lc=&pullStatus=0'